<?php

namespace App\Repositories;

use App\Http\Resources\ProjectCollection;
use App\Http\Resources\ProjectResource;
use App\Models\Project;
use App\Repositories\BaseRepository;

/**
 * Class ProjectRepository
 * @package App\Repositories
 * @version January 5, 2021, 4:18 pm UTC
*/

class ProjectRepository extends BaseRepository
{
    /**
     * @var array
     */
    protected $fieldSearchable = [
        'ProjectTitle',
        'ProjectAbstract',
        'Researcher_ID',
        'User_ID',
        'ProjectResearchAreas',
        'ResearchersInvolved',
        'Funded',
        'Funder_ID',
        'Status',
        'LinkToPublication',
        'Access_Level',
        'projectStart',
        'projectEnd',
        'abstractDocumentPath',
        'otherProjectDocsPath',
        'RelevantProjectDocuments'
    ];

    /**
     * Return searchable fields
     *
     * @return array
     */
    public function getFieldsSearchable()
    {
        return $this->fieldSearchable;
    }

    /**
     * Configure the Model
     **/
    public function model()
    {
        return Project::class;
    }

    public function all($search = [], $skip = null, $limit = null, $columns = ['*'])
    {
        return parent::all($search, $skip, $limit, $columns); // TODO: Change the autogenerated stub
    }

    public function paginate($perPage, $columns = ['*'])
    {
        return parent::paginate($perPage, $columns); // TODO: Change the autogenerated stub
    }
}
