<?php

namespace App\Repositories;

use App\Models\Publication;

/**
 * Class PublicationRepository
 * @package App\Repositories
 * @version January 4, 2021, 12:13 pm UTC
 */
class PublicationRepository extends BaseRepository
{
    /**
     * @var array
     */
    protected $fieldSearchable = [
        'UserID',
        'Researcher_ID',
        'PublicationTitle',
        'PublicationPath',
        'DateOfPublication',
        'Collaborators',
        'PublicationURL',
        'Access_Level'
    ];

    /**
     * Return searchable fields
     *
     * @return array
     */
    public function getFieldsSearchable()
    {
        return $this->fieldSearchable;
    }

    /**
     * Configure the Model
     **/
    public function model()
    {
        return Publication::class;
    }

    public function create($input)
    {
        return parent::create($input); // TODO: Change the autogenerated stub
    }

    public function update($input, $id)
    {
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function all($search = [], $skip = null, $limit = null, $columns = ['*'])
    {
        return parent::all($search, $skip, $limit, $columns); // TODO: Change the autogenerated stub
    }

    public function find($id, $columns = ['*'])
    {
        return parent::find($id, $columns); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function latest()
    {
        return parent::all();
    }

    public function summary($type = '')
    {
        return $summary = [
            'publications_count' => Publication::all()->count(),
            'latest_publications' => Publication::latestPublications()
        ];
    }

    public function paginate($perPage, $columns = ['*'])
    {
        return parent::paginate($perPage, $columns); // TODO: Change the autogenerated stub
    }
}
